// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RwqsgK7gBMO6cMijcUD388FBMHwXaLc',
    appId: '1:804456786215:web:95a9796efa5a4c1afee102',
    messagingSenderId: '804456786215',
    projectId: 'project-7765481086774765519',
    authDomain: 'project-7765481086774765519.firebaseapp.com',
    storageBucket: 'project-7765481086774765519.appspot.com',
    measurementId: 'G-PSCK139NGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIXCTKCwdn54HxUchJiIOyMPkwDCfnmv0',
    appId: '1:804456786215:android:670ffc9588a7bff3fee102',
    messagingSenderId: '804456786215',
    projectId: 'project-7765481086774765519',
    storageBucket: 'project-7765481086774765519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC116v-FujnEOFizfxtjLu6cvUXlA2UNi8',
    appId: '1:804456786215:ios:a6edf1d23c2e340afee102',
    messagingSenderId: '804456786215',
    projectId: 'project-7765481086774765519',
    storageBucket: 'project-7765481086774765519.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC116v-FujnEOFizfxtjLu6cvUXlA2UNi8',
    appId: '1:804456786215:ios:a6edf1d23c2e340afee102',
    messagingSenderId: '804456786215',
    projectId: 'project-7765481086774765519',
    storageBucket: 'project-7765481086774765519.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8RwqsgK7gBMO6cMijcUD388FBMHwXaLc',
    appId: '1:804456786215:web:36483942f822a052fee102',
    messagingSenderId: '804456786215',
    projectId: 'project-7765481086774765519',
    authDomain: 'project-7765481086774765519.firebaseapp.com',
    storageBucket: 'project-7765481086774765519.appspot.com',
    measurementId: 'G-QLX9TJCX5S',
  );

}